### ISSUE TITLE
can you backport to 1.17

### ISSUE THREAD

**Issue by RYUKxAnime** [illusivesoulworks/elytrautilities#8]
### What is the new feature or improvement?

just Toggle Elytra Flight feature would be more than enough please
or just a standalone mod that does this would be very very appreciated

**Comment by TheIllusiveC4** [comment]
Please do not make duplicate requests. I have already given you an answer to this in https://github.com/illusivesoulworks/elytrautilities/issues/7. The amount of work needed to port the mod is not significantly different even if it's just for one of the features. In addition, the main reason is because 1.17 is old now and does not have a big enough player base to warrant porting to it.
